services:
  keycloak-db:
    image: postgres:16
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_pass
    networks:
      - backend
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.2
    command: start-dev --http-port=8180 --import-realm --bootstrap-admin-username tmpadm --bootstrap-admin-password pass
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak_pass
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - ./src/test/resources/postman/keycloak:/opt/keycloak/data/import
    depends_on:
      - keycloak-db
    ports:
      - "8180:8180"
    networks:
      - backend

  car-service-test-db:
    image: postgres:16
    environment:
      POSTGRES_DB: car_service_db
      POSTGRES_USER: car_service_db_user
      POSTGRES_PASSWORD: car_service_db_password
    networks:
      - backend
    volumes:
      - car-service-db-data:/var/lib/postgresql/data

  flyway-car-service:
    image: flyway/flyway:11.8-azure
    environment:
      FLYWAY_URL: jdbc:postgresql://car-service-test-db:5432/car_service_db
      FLYWAY_USER: car_service_db_user
      FLYWAY_PASSWORD: car_service_db_password
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
      FLYWAY_SCHEMAS: public
    volumes:
      - ./src/test/resources/postman/db/migration:/flyway/sql
    entrypoint: >
      /bin/bash -c "
      for i in {1..10}; do
        if echo > /dev/tcp/car-service-test-db/5432; then
          flyway migrate && exit 0;
        fi;
        echo 'Waiting for car-service-test-db to be ready...';
        sleep 5;
      done;
      echo 'Database not ready after 50 seconds' && exit 1;"
    depends_on:
      - car-service-test-db
    networks:
      - backend

  car-service:
    container_name: car-service
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: car-service-test-db
      DB_PORT: 5432
      DB_NAME: car_service_db
      DB_USER: car_service_db_user
      DB_PASSWORD: car_service_db_password
    entrypoint: sh
    command: /src/test/resources/postman/car-service-runner.sh
    volumes:
      - ${CI_PROJECT_DIR}/src/test/resources/postman:/src/test/resources/postman
    depends_on:
      - keycloak
      - car-service-test-db
      - flyway-car-service
    ports:
      - "8080:8080"
    networks:
      - backend

  postman-tests:
    container_name: postman-tests
    image: postman/newman:6-alpine
    entrypoint: sh
    command: /resources/postman-runner.sh
    volumes:
      - ./src/test/resources/postman:/resources
    depends_on:
      - car-service
    networks:
      - backend

networks:
  backend:

volumes:
  keycloak-db-data:
  car-service-db-data:
